### ISSUE TITLE
jpegxl images not rendering

### ISSUE THREAD

**Issue by castrojo** [castrojo/achillobator#12]
I wonder if there's a build/codec difference on this one, they render fine in the image viewer, they just don't show up on the desktop or the wallpaper widget.

**Comment by castrojo** [comment]
libjxl is in the main image now, we just need to check that it works, and then change the wallpapers back to jxl.

**Comment by hanthor** [comment]
the background is doing that gray thing like it did on F41 release

**Comment by castrojo** [comment]
We added the libjxl library but that wasn't enough - my next guess is checking if the wallpaper capplet thing was built with support for it.

**Comment by hanthor** [comment]
" Don't recommend avif and jxl loaders on RHEL"
https://packages.fedoraproject.org/pkgs/gdk-pixbuf2/gdk-pixbuf2-modules/fedora-40.html

**Comment by hanthor** [comment]
Wee need https://packages.fedoraproject.org/pkgs/jpegxl/jxl-pixbuf-loader/

**Comment by tulilirockz** [comment]
Its working just fine now, libjxl brings in `jxl-pixbuf-loader` and makes it work.

https://github.com/user-attachments/assets/2425e417-88b3-4387-8cd4-e36b69d1ba63
