### ISSUE TITLE
Use uupd for updates

### ISSUE THREAD

**Issue by castrojo** [castrojo/achillobator#13]
Let's use https://github.com/ublue-os/uupd for the updates.

- We need to smoke test it for the other images anyway
- It'll be easier/cleaner to not bring all those old service units here for flatpak, brew, rpm-ostree, etc.

**Comment by tulilirockz** [comment]
https://github.com/ublue-os/uupd/pull/42 should be literally the last step to adding this. The RPM seems to build fine, everything looks good, we can just create a COPR and add it here and BAM, done for testing

**Comment by gerblesh** [comment]
All merged if you want to start trying it out, released under a "prerelease" but once I get around to testing it I'll probably make an official v1.0 release
