### ISSUE TITLE
Building ISO's

### ISSUE THREAD

**Issue by hanthor** [castrojo/achillobator#14]
got an ISO to build with the following:

build bootc-image-builder from github

```
sudo podman image scp $USER@localhost::bib:dev root@localhost::
sudo rm -rf output || true
mkdir -p output
sudo podman run \
  --rm \
  -it \
  --privileged \
  --pull=newer \
  --security-opt label=type:unconfined_t \
  --network=host \
  -v $(pwd)/output:/output \
  -v /var/lib/containers/storage:/var/lib/containers/storage \
  localhost/bib:dev \
  --type iso \
  --local \
  localhost/achillobator:latest
```

need https://discord.com/channels/1072614816579063828/1318955957509685298/1319318448592912417 in the image for `bib` to work as-is

**Comment by detiber** [comment]
This should be resolved with the latest tooling changes, and using an image built from our bootc-image-builder fork: https://github.com/centos-workstation/bootc-image-builder
