### ISSUE TITLE
need to cleanup the previous osbuild manifests not just the iso/image

### ISSUE THREAD

**Issue by hanthor** [castrojo/achillobator#30]
https://github.com/centos-workstation/achillobator/blob/97076270becbc5ed0628f6eeca3892e8a9e82815/Justfile#L139-L144

**Comment by hanthor** [comment]
could we just run just clean?

https://github.com/centos-workstation/achillobator/blob/97076270becbc5ed0628f6eeca3892e8a9e82815/Justfile#L42-L51

**Comment by tulilirockz** [comment]
Id just remove the output directory straight up

**Comment by hanthor** [comment]
yes that's what I've been doing, but this was a bit of a red herring. Not a real issue, it would be nice to not delete your qcow when you build a iso
