### ISSUE TITLE
Minimum Viable Image goals and features

### ISSUE THREAD

**Issue by tulilirockz** [castrojo/achillobator#8]
This is an unordered list of all the stuff we want to do in this for now

- [x] Just! (?) (just needs to be ported to EPEL)
- [x] Rechunking (will get added to main and here soon)
- [ ] Secure Boot?
- [x] #24

Homebrew:
- [x] Add it to the image
- [x] #18 

Theming:
- [x] Most stuff is already done (+dconf)
- [x] MOTD (just needs to add image-info.json and change some stuff in os-release)
- [x] Fastfetch? (will get added to EPEL) (#23)
- [x] Extensions (blur-my-shell, logo-menu and dash-to-dock)
- [ ] Wallpapers (i really think we should use a COPR for this.)
- [x] Documentation/Ublue shortcuts + icons
- [x] Nerdfonts! Probably through a COPR

ISO:
- [ ] https://github.com/rhinstaller/anaconda/pull/6056
- [x] Bootc Image Builder centos 10 fix
- [ ] Bootc Image Builder needs to have a way to install flatpaks in it
- [x] (#25)
- [ ] Branding
- [x] Workflows for Github intergrated with Cloudflare

UUPD:
- [x] Needs some discussion about how we can implement the progress bar or if we should even have progress bars for it
- [x] Needs to get the testing + logging PR merged
- [x] #35

**Comment by castrojo** [comment]
For MVP let's do:

desktop/artwork (missing extensions is fine but let's get logomenu with the `u` in there), homebrew, rechunker, and the ISO (which can have the flatpaks). 

Let's call that an MVP and then we can announce it, let people drive for a while, etc. Then we can start adding the packages, etc.

**Comment by tulilirockz** [comment]
I believe most of the stuff we wanted as a MVP was already done, I moved a few of the non-critical issues to separate issues. Amazing work you all.
