### ISSUE TITLE
Add tailscale

### ISSUE THREAD

**Issue by hanthor** [castrojo/achillobator#9]
3 options for Tailscale:

1. get it moved into Centos in EPEL(it's already there for fedora)
2. add the repo like bluefin
3. make a systemd-sysext for tailfin already mostly written here: https://tailscale.com/blog/steam-deck

Should we add the gnome extension?

**Comment by hanthor** [comment]
It's already in EPEL!

**Comment by tulilirockz** [comment]
Added it! We do need the extension now tho

**Comment by hanthor** [comment]
Not doing the extension, people can add it themselves I guess
